Train:
  epochs: 20
  batch_size: 32
  save_rate: 2
  learning_rate: 0.0001
  path_to_dataset: "../../drive/MyDrive/ThousandWordsAnImage/data/Images"
  path_to_labels: "../../drive/MyDrive/ThousandWordsAnImage/data/labels.csv"
  ref_image_path: "../../drive/MyDrive/ThousandWordsAnImage/data/ref-image.jpg"

network:
  model: Encoder
  tokenizer: gpt2
